<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="daGiMa_MDE_HW3" nsURI="http://www.example.org/dagima_mde_hw3"
    nsPrefix="dagima_mde_hw3">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="University">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rector" lowerBound="1"
        eType="#//Professor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="departments" lowerBound="1"
        upperBound="-1" eType="#//Department" containment="true" eOpposite="#//Department/university"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="A university" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Professor" eSuperTypes="#//User">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="satisfyMinimalCfuRequirement"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="satisfyMinimalCfuRequirement" value="&#xA;&#x9;&#x9;&#x9;totalCfuTaught() >= 15"/>
    </eAnnotations>
    <eOperations name="totalCfuTaught" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="body" value="taught_courses->collect(course|course.cfu)->sum()"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="office_telephone" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orcid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinated_degree_courses"
        upperBound="-1" eType="#//DegreeCourse" eOpposite="#//DegreeCourse/coordinator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supervised_thesis" upperBound="-1"
        eType="#//Thesis" eOpposite="#//Thesis/supervisor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taught_courses" lowerBound="1"
        upperBound="-1" eType="#//Course" eOpposite="#//Course/teachers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="news_posted" upperBound="-1"
        eType="#//News" containment="true" eOpposite="#//News/author"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Student" eSuperTypes="#//User">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="property student_exams : Course[*] { ordered derived volatile } {&#xA;derivation : transcripts->collect(transcript|transcript.courses.course)->asOrderedSet();&#xA;}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="matriculation_number" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thesis_defended" upperBound="-1"
        eType="#//Thesis" containment="true" eOpposite="#//Thesis/student"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enrolled_courses" upperBound="-1"
        eType="#//DegreeCourse" eOpposite="#//DegreeCourse/enrolled_students"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="booked_calls" upperBound="-1"
        eType="#//ExaminationCall" eOpposite="#//ExaminationCall/booked_students"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transcripts" upperBound="-1"
        eType="#//Career" containment="true" eOpposite="#//Career/student"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="surname" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="telephone" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="all_contacts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="email.concat(' - ').concat(telephone).concat(if(self.oclIsTypeOf(Professor)) then ' - '.concat(self.oclAsType(Professor).office_telephone) else '' endif)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birth_date" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Department">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="property teachers : Professor[*] { ordered derived volatile } {&#xA;derivation : offered_courses->collect(degree_course|degree_course.course_catalogue.teachers)->asOrderedSet();&#xA;}"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="website" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="offered_courses" lowerBound="1"
        upperBound="-1" eType="#//DegreeCourse" containment="true" eOpposite="#//DegreeCourse/department"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="university" eType="#//University"
        eOpposite="#//University/departments"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="A department" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="related_news" upperBound="-1"
        eType="#//News" eOpposite="#//News/department"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DegreeCourse">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="cfuBetweenValues"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="cfuBetweenValues" value="&#xA;&#x9;&#x9;&#x9;cfu > 0 and cfu &lt;= 360"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="L-44" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="A degree course"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reference_year" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="2023"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="3"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cfu" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="180"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="A description of this course"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="English"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="department" eType="#//Department"
        eOpposite="#//Department/offered_courses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinator" lowerBound="1"
        eType="#//Professor" eOpposite="#//Professor/coordinated_degree_courses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enrolled_students" upperBound="-1"
        eType="#//Student" eOpposite="#//Student/enrolled_courses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="course_catalogue" lowerBound="1"
        upperBound="-1" eType="#//Course" eOpposite="#//Course/degree_courses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extra_info" upperBound="-1"
        eType="#//ExtraInfo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Thesis">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="checkIfEnoughCreditsToGraduate"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="checkIfEnoughCreditsToGraduate" value="&#xA;&#x9;&#x9;&#x9;student.transcripts->select(transcript|transcript.degree_course = self.degree_course)->forAll(e|e.passedAllExams())"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="A thesis" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//ThesisType"
        defaultValueLiteral="COMPILATION"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="student" lowerBound="1"
        eType="#//Student" eOpposite="#//Student/thesis_defended"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supervisor" lowerBound="1"
        eType="#//Professor" eOpposite="#//Professor/supervised_thesis"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="degree_course" lowerBound="1"
        eType="#//DegreeCourse"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ThesisType">
    <eLiterals name="COMPILATION"/>
    <eLiterals name="EXPERIMENTAL" value="1"/>
    <eLiterals name="PUBLICATION" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="cfuCourseGreaterThan"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="cfuCourseGreaterThan" value="&#xA;&#x9;&#x9;&#x9;cfu > 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="F-1234" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="A course"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="English"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cfu" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="6"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credit_type" lowerBound="1"
        eType="#//CreditType" defaultValueLiteral="B"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="2"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="period" lowerBound="1"
        eType="#//CoursePeriod" defaultValueLiteral="FIRST_SEMESTER"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teachers" lowerBound="1"
        upperBound="-1" eType="#//Professor" eOpposite="#//Professor/taught_courses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="degree_courses" lowerBound="1"
        upperBound="-1" eType="#//DegreeCourse" eOpposite="#//DegreeCourse/course_catalogue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calls" upperBound="-1"
        eType="#//ExaminationCall" containment="true" eOpposite="#//ExaminationCall/course"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="students_grades" upperBound="-1"
        eType="#//PassingGrade" eOpposite="#//PassingGrade/course"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extra_info" upperBound="-1"
        eType="#//ExtraInfo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CreditType">
    <eLiterals name="B" value="1"/>
    <eLiterals name="C" value="2"/>
    <eLiterals name="D" value="3"/>
    <eLiterals name="E" value="4"/>
    <eLiterals name="F" value="5" literal="F"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CoursePeriod">
    <eLiterals name="FIRST_SEMESTER"/>
    <eLiterals name="SECOND_SEMESTER" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExaminationCall">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
        defaultValueLiteral="2024-01-28"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classroom" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//ExamType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="An exam call description"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="course" lowerBound="1"
        eType="#//Course" eOpposite="#//Course/calls"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="booked_students" upperBound="-1"
        eType="#//Student" eOpposite="#//Student/booked_calls"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ExamType">
    <eLiterals name="WRITTEN"/>
    <eLiterals name="ORAL" value="1"/>
    <eLiterals name="PROJECT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PassingGrade">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="mustBeSufficientIfDefined"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="mustBeSufficientIfDefined" value="&#xA;&#x9;&#x9;&#x9;grade.size() = 0 or (grade.matches('([Aa][+]{0,1}){1}|[B-Db-d]{1}|(1[8-9]{1}|2[0-9]{1}|30[Ll]{0,1}){1}'))"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
        defaultValueLiteral="2024-01-28" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="grade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="30"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="course" lowerBound="1"
        eType="#//Course" eOpposite="#//Course/students_grades"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="student" lowerBound="1"
        eType="#//Career" eOpposite="#//Career/courses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Career">
    <eOperations name="passedAllExams" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="body" value="courses->forAll(course|course.grade.size() > 0)"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="New transcript"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="student" lowerBound="1"
        eType="#//Student" eOpposite="#//Student/transcripts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="degree_course" lowerBound="1"
        eType="#//DegreeCourse"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//PassingGrade" containment="true" eOpposite="#//PassingGrade/student"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalAcquiredCfu" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"
        volatile="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="derivation" value="courses->select(transcriptEntry | transcriptEntry.grade.size() > 0)->collect(passingGrade | passingGrade.course.cfu)->sum()"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="News">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="A news title" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publication_date" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate" defaultValueLiteral="2023-12-18"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="department" eType="#//Department"
        eOpposite="#//Department/related_news"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" lowerBound="1"
        eType="#//Professor" eOpposite="#//Professor/news_posted"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut porta ante id turpis faucibus pharetra non nec arcu. Morbi luctus, est at tincidunt scelerisque, eros purus posuere purus, in facilisis turpis lectus et neque. Phasellus euismod accumsan turpis faucibus lobortis. In eleifend ligula non iaculis pulvinar. Nulla malesuada ac massa vulputate molestie."/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtraInfo">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="stringTypeCheck integerTypeCheck floatTypeCheck doubleTypeCheck booleanTypeCheck enumTypeCheck"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="stringTypeCheck" value="&#xA;&#x9;&#x9;&#x9;value.oclIsTypeOf(String) or type &lt;> MetadataType::STRING"/>
      <details key="integerTypeCheck" value="&#xA;&#x9;&#x9;&#x9;value.matches('[0-9]+') or type &lt;> MetadataType::INTEGER"/>
      <details key="floatTypeCheck" value="&#xA;&#x9;&#x9;&#x9;value.matches('[0-9]+([.]{1}[0-9]+)?[Ff]') or type &lt;> MetadataType::FLOAT"/>
      <details key="doubleTypeCheck" value="&#xA;&#x9;&#x9;&#x9;value.matches('[0-9]+([.]{1}[0-9]+)?[Dd]') or type &lt;> MetadataType::DOUBLE"/>
      <details key="booleanTypeCheck" value="&#xA;&#x9;&#x9;&#x9;value.matches('^true|false$') or type &lt;> MetadataType::BOOLEAN"/>
      <details key="enumTypeCheck" value="&#xA;&#x9;&#x9;&#x9;enum?.values->one(enumValue | enumValue = value) or type &lt;> MetadataType::ENUMERATION"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//MetadataType"
        defaultValueLiteral="STRING"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower_multiplicity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="higher_multiplicity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enum" eType="#//CustomEnumeration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MetadataType">
    <eLiterals name="STRING"/>
    <eLiterals name="INTEGER" value="1"/>
    <eLiterals name="BOOLEAN" value="2"/>
    <eLiterals name="FLOAT" value="3"/>
    <eLiterals name="DOUBLE" value="4"/>
    <eLiterals name="ENUMERATION" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomEnumeration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="values" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="universities" upperBound="-1"
        eType="#//University" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="professors" upperBound="-1"
        eType="#//Professor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="students" upperBound="-1"
        eType="#//Student" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="custom_enumerations" upperBound="-1"
        eType="#//CustomEnumeration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extra_infos" upperBound="-1"
        eType="#//ExtraInfo" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="model_name" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="NewModel"
        unsettable="true"/>
  </eClassifiers>
</ecore:EPackage>
